### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ungoldman** [lyzidiamond/centroids#8]
Project needs a license so people know what they can & can't do with it! Here are some good ones: http://opensource.org/licenses

**Comment by ngoldman** [comment]
:wave:

**Comment by lyzidiamond** [comment]
This is a good reminder, thanks @ngoldman. I will do this tomorrow.

**Comment by ungoldman** [comment]
😭

**Comment by ungoldman** [comment]
Here is my favorite license, adapted for your use as a `LICENSE.md` file:

```
# [ISC License](https://spdx.org/licenses/ISC)

Copyright (c) 2016, Lyzi Diamond <lyzidiamond@gmail.com>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

Some other great open source licenses include:

- [MIT](spdx.org/licenses/MIT)
- [CC-1.0](https://spdx.org/licenses/CC0-1.0.html)

An exhaustive list is available here:

https://spdx.org/licenses/

**Comment by lyzidiamond** [comment]
I appreciate your persistence here.

**Comment by ungoldman** [comment]
Yay!

TBH I am mainly trying to get the `Open` number to go for down for myself on https://github.com/issues. Every few weekends I go through and try to see if I can resolve one or two.

![screen shot 2016-12-04 at 5 57 14 pm](https://cloud.githubusercontent.com/assets/427322/20871481/343f85dc-ba4b-11e6-91a0-f794c86a5590.png)

**Comment by lyzidiamond** [comment]
I know this feel

<img width="243" alt="screen shot 2016-12-04 at 6 01 00 pm" src="https://cloud.githubusercontent.com/assets/2523165/20871535/aa7c4c8a-ba4b-11e6-8497-fb69c43bf7c3.png">

**Comment by ungoldman** [comment]
When you leave an org the number goes down 😁
